services:
  postgres:
    image: postgres:14
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  redis:
    build:
      context: ./redis
      args:
        REDIS_PASSWORD: ${REDIS_PASSWORD}
        REDIS_USER: ${REDIS_USER}
        REDIS_USER_PASSWORD: ${REDIS_USER_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis_data:/data
